### ISSUE TITLE
This looks kind of jacked, have I missed something?

### ISSUE THREAD

**Issue by hoff2** [kreativgebiet/rich#101]
Didn't know any other way to contact you but I am trying to use rich in Active Admin pretty much as you describe in the README but the layout seems kind of funky to me, or at least not like the screenshot
![screen shot 2013-10-07 at 5 09 01 pm](https://f.cloud.github.com/assets/130212/1284903/f596ad96-2f9d-11e3-95c8-2aaa13fd627c.png)
. Or maybe this is how it's supposed to look. I did add //= require rich/editor to app/assets/stylesheets/active_admin.css.scss as well

**Comment by joeswann** [comment]
Hi, have this exact issue. Was a solution ever found?

**Comment by hoff2** [comment]
see @macowie comment above: https://github.com/kreativgebiet/rich/issues/101#issuecomment-26060233
