### ISSUE TITLE
formtastic 3.0 support  

### ISSUE THREAD

**Issue by Nimdis** [kreativgebiet/rich#166]
Hello!
Thanks for great gem!
I've been working around a project which uses last version of activeadmin from github (1.0.0.pre). So its version depends on formtastic 3.0.
After installing of rich I got an error when my project couldn't find rich_input. This issue was in file app/inputs/rich_input.rb and looked like

    if (Object.const_defined?("Formtastic") && Gem.loaded_specs["formtastic"].version.version[0,1] == "2")

As I know this line means that that version of formtastic is locked to 2.x
I've written a monkey patch and fixed 2 to 3. 
After that everything works fine.
Would be great to fix this issue.
Thanks!

ps: sorry if somewhere was errors in my english =)

**Comment by nicpillinger** [comment]
is likely to get merged in? its a pain as activeadmin 1.0pre won't work until this is in.

**Comment by forsaken1** [comment]
@nicpillinger, 
![-3](https://cloud.githubusercontent.com/assets/1580566/5869579/b6f26af0-a2fe-11e4-8d38-3f387a4cf0b4.png)
Small bug with Formtastic 3.x, I try fix it...

**Comment by iDuuck** [comment]
Merged.
