### ISSUE TITLE
Uncaught TypeError: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by nachokb** [kreativgebiet/rich#94]
This is a Rails 3.2 app with ActiveAdmin. Using Rich 1.4.6.

Can't make it work, keeps throwing this error in initStyles().

Also, require 'rich' could not find it, had to use require 'rich/application'...

**Comment by fidenz-oshan** [comment]
i am having the same issue here. using rich 1.4.8 from master branch, rails 4.2 with active admin.
beside that error js console is clear. 
rich file picker isn't open in separate window. it just redirect to URL. 

found that rich generated script has an issue.

``` javascript
<li class="rich_picker input optional stringish" id="benefit_image_input">
<label for="benefit_rich_rich_file_id" class="label">Image</label>
<input class="rich-picker" style="width: 400px !important;" id="benefit_rich_rich_file_id" type="text" name="benefit[image]" />
            <a href='/rich/files/' class='button'>
              Select or upload
            </a>

            <script>
              $(function(){
                $('#benefit_rich_rich_file_id_input a').click(function(e){
```

so generated button selector isn't match with the elements.
this is the active admin form code

``` ruby
f.inputs 'Image' do
  f.input :image, as: :rich_picker, config: { style: 'width: 400px !important;' }
end
```

and model

``` ruby
class Benefit < ActiveRecord::Base
  belongs_to :image, class_name: 'Rich::RichFile', foreign_key: 'rich_rich_file_id'
```

**Comment by fidenz-oshan** [comment]
found the solution its because my relation name deffer from the column name. so $('#benefit_rich_rich_file_id_input a') wasn't working.
